export interface CarListing {
  id: string;
  title: string;
  brand: string;
  model: string;
  year: number;
  price: number;
  km: number;
  fuel: string;
  transmission: string;
  power: string;
  source: "autoscout24" | "subito" | "automobile" | "brumbrum";
  allSources?: string[];
  imageUrl: string;
  location: string;
  isNew: boolean;
  url: string;
  isBestDeal?: boolean;
  priceRating?: "best" | "good" | "normal";
  color: string;
  doors: number;
  bodyType: string;
}

export const carBrands = [
  "Audi",
  "BMW",
  "Fiat",
  "Ford",
  "Jeep",
  "Mercedes-Benz",
  "Opel",
  "Peugeot",
  "Renault",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "Alfa Romeo",
  "Citroën",
  "Dacia",
  "Hyundai",
  "Kia",
  "Mazda",
  "Nissan",
  "Seat",
  "Škoda",
  "Tesla",
  "Mini",
  "Porsche",
  "Land Rover",
];

export const brandModels: Record<string, string[]> = {
  BMW: ["Serie 1", "Serie 2", "Serie 3", "Serie 4", "Serie 5", "X1", "X3", "X5", "iX"],
  Audi: ["A1", "A3", "A4", "A5", "A6", "Q3", "Q5", "Q7", "e-tron"],
  "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe E", "GLA", "GLC", "GLE", "EQA"],
  Volkswagen: ["Golf", "Polo", "T-Roc", "Tiguan", "T-Cross", "Passat", "ID.3", "ID.4"],
  Fiat: ["500", "500X", "Panda", "Tipo", "600", "Punto"],
  Toyota: ["Yaris", "Yaris Cross", "Corolla", "C-HR", "RAV4", "Aygo X"],
  Ford: ["Fiesta", "Focus", "Puma", "Kuga", "Mustang Mach-E"],
  Renault: ["Clio", "Captur", "Mégane", "Arkana", "Austral"],
  Peugeot: ["208", "308", "2008", "3008", "5008", "e-208"],
  Hyundai: ["i10", "i20", "i30", "Tucson", "Kona", "IONIQ 5"],
  Kia: ["Picanto", "Rio", "Ceed", "Sportage", "Niro", "EV6"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X"],
  Jeep: ["Renegade", "Compass", "Avenger", "Wrangler"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "Junior"],
  Volvo: ["XC40", "XC60", "XC90", "C40", "EX30"],
  Opel: ["Corsa", "Astra", "Mokka", "Crossland", "Grandland"],
  Citroën: ["C3", "C4", "C5 Aircross", "ë-C4"],
  Dacia: ["Sandero", "Duster", "Jogger", "Spring"],
  Mazda: ["Mazda2", "Mazda3", "CX-30", "CX-5", "MX-5"],
  Nissan: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya"],
  Seat: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"],
  Škoda: ["Fabia", "Octavia", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  Mini: ["Cooper", "Countryman", "Clubman"],
  Porsche: ["Cayenne", "Macan", "Taycan", "911", "Panamera"],
  "Land Rover": ["Evoque", "Velar", "Sport", "Defender", "Discovery"],
};

export const modelTrims: Record<string, Record<string, string[]>> = {
  BMW: {
    "Serie 1": ["116d", "118i", "120d xDrive", "M135i xDrive"],
    "Serie 2": ["218i", "220d", "220d xDrive", "M235i xDrive"],
    "Serie 3": ["316d", "318d", "320d", "320d xDrive", "330i", "330e", "M340i xDrive"],
    "Serie 4": ["420d", "420d xDrive", "430i", "M440i xDrive"],
    "Serie 5": ["520d", "520d xDrive", "530i", "530e", "M550i xDrive"],
    X1: ["sDrive18d", "xDrive20d", "xDrive25e"],
    X3: ["xDrive20d", "xDrive30d", "xDrive30e", "M40i"],
    X5: ["xDrive30d", "xDrive40d", "xDrive45e", "M50i"],
    iX: ["xDrive40", "xDrive50", "M60"],
  },
  Audi: {
    A1: ["25 TFSI", "30 TFSI", "35 TFSI", "S1"],
    A3: ["30 TFSI", "35 TFSI", "35 TDI", "40 TFSI e", "S3", "RS3"],
    A4: ["30 TDI", "35 TFSI", "40 TDI", "45 TFSI", "S4", "RS4"],
    A5: ["35 TFSI", "40 TDI", "45 TFSI", "S5", "RS5"],
    A6: ["40 TDI", "45 TFSI", "50 TDI", "55 TFSI e", "S6", "RS6"],
    Q3: ["35 TFSI", "35 TDI", "45 TFSI e"],
    Q5: ["40 TDI", "45 TFSI", "55 TFSI e", "SQ5"],
    Q7: ["45 TDI", "50 TDI", "55 TFSI e", "SQ7"],
    "e-tron": ["50", "55", "S", "GT"],
  },
  "Mercedes-Benz": {
    "Classe A": ["A 160", "A 180", "A 200", "A 200d", "A 250", "A 250e", "AMG A 35", "AMG A 45 S"],
    "Classe B": ["B 160", "B 180", "B 200", "B 200d", "B 250e"],
    "Classe C": ["C 180", "C 200", "C 220d", "C 300", "C 300e", "AMG C 43", "AMG C 63"],
    "Classe E": ["E 200", "E 220d", "E 300", "E 300e", "AMG E 53", "AMG E 63 S"],
    GLA: ["GLA 180", "GLA 200", "GLA 200d", "GLA 250e", "AMG GLA 35", "AMG GLA 45 S"],
    GLC: ["GLC 200", "GLC 220d", "GLC 300", "GLC 300e", "AMG GLC 43", "AMG GLC 63"],
    GLE: ["GLE 300d", "GLE 350d", "GLE 450", "GLE 350de", "AMG GLE 53", "AMG GLE 63 S"],
    EQA: ["EQA 250", "EQA 300", "EQA 350"],
  },
  Volkswagen: {
    Golf: ["1.0 TSI", "1.5 TSI", "1.5 eTSI", "2.0 TDI", "GTE", "GTI", "GTI Clubsport", "R"],
    Polo: ["1.0 MPI", "1.0 TSI", "1.0 TGI", "GTI"],
    "T-Roc": ["1.0 TSI", "1.5 TSI", "2.0 TDI", "2.0 TSI R"],
    Tiguan: ["1.5 TSI", "2.0 TDI", "2.0 TSI", "1.4 eHybrid", "R"],
    "T-Cross": ["1.0 TSI", "1.5 TSI", "1.6 TDI"],
    Passat: ["1.5 TSI", "2.0 TDI", "1.4 GTE"],
    "ID.3": ["Pure", "Pro", "Pro S", "GTX"],
    "ID.4": ["Pure", "Pro", "Pro S", "GTX"],
  },
  Fiat: {
    "500": ["1.0 Hybrid", "Elettrica 23.8 kWh", "Elettrica 42 kWh", "Abarth"],
    "500X": ["1.0 T3", "1.3 T4", "1.6 MultiJet", "1.3 T4 PHEV"],
    Panda: ["1.0 Hybrid", "0.9 TwinAir", "1.2", "Cross", "4x4"],
    Tipo: ["1.0 T3", "1.3 MultiJet", "1.6 MultiJet", "Cross"],
    "600": ["Elettrica", "Ibrida"],
    Punto: ["1.2", "1.3 MultiJet", "1.4 T-Jet"],
  },
  Tesla: {
    "Model 3": ["Standard Range", "Long Range", "Performance"],
    "Model Y": ["Standard Range", "Long Range", "Performance"],
    "Model S": ["Long Range", "Plaid"],
    "Model X": ["Long Range", "Plaid"],
  },
  Toyota: {
    Yaris: ["1.0", "1.5", "1.5 Hybrid"],
    "Yaris Cross": ["1.5 Hybrid", "1.5 Hybrid AWD"],
    Corolla: ["1.8 Hybrid", "2.0 Hybrid"],
    "C-HR": ["1.8 Hybrid", "2.0 Hybrid", "2.0 Plug-in Hybrid"],
    RAV4: ["2.5 Hybrid", "2.5 Plug-in Hybrid"],
    "Aygo X": ["1.0"],
  },
};

export const fuelTypes = ["Benzina", "Diesel", "Elettrica", "Ibrida", "GPL", "Metano"];
export const transmissionTypes = ["Manuale", "Automatico"];
export const carColors = [
  "Nero",
  "Bianco",
  "Grigio",
  "Blu",
  "Rosso",
  "Argento",
  "Verde",
  "Marrone",
];
export const doorOptions = [2, 3, 4, 5];
export const bodyTypes = [
  "Berlina",
  "SUV",
  "Station Wagon",
  "Coupé",
  "Monovolume",
  "Cabrio",
  "Citycar",
  "Crossover",
];

export const sourceLabels: Record<string, string> = {
  autoscout24: "AutoScout24",
  subito: "Subito.it",
  automobile: "Automobile.it",
  brumbrum: "Brumbrum",
};

export const sourceColors: Record<string, string> = {
  autoscout24: "bg-[hsl(var(--source-autoscout))]",
  subito: "bg-[hsl(var(--source-subito))]",
  automobile: "bg-[hsl(var(--source-automobile))]",
  brumbrum: "bg-[hsl(var(--source-brumbrum))]",
};

const images = [
  "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&q=80",
  "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600&q=80",
  "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80",
  "https://images.unsplash.com/photo-1542362567-b07e54358753?w=600&q=80",
  "https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=600&q=80",
  "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=600&q=80",
];

const bmwImages = [
  "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=80",
  "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=600&q=80",
  "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600&q=80",
  "https://images.unsplash.com/photo-1556189250-72ba954cfc2b?w=600&q=80",
  "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&q=80",
  "https://images.unsplash.com/photo-1619362280286-f1f8fd5032ed?w=600&q=80",
];

export const mockListings: CarListing[] = [
  {
    id: "1",
    title: "BMW Serie 3 320d xDrive",
    brand: "BMW",
    model: "Serie 3",
    year: 2021,
    price: 28500,
    km: 45000,
    fuel: "Diesel",
    transmission: "Automatico",
    power: "190 CV",
    source: "autoscout24",
    imageUrl: bmwImages[0],
    location: "Milano, MI",
    isNew: false,
    url: "#",
    isBestDeal: true,
    priceRating: "best",
    color: "Nero",
    doors: 4,
    bodyType: "Berlina",
  },
  {
    id: "2",
    title: "BMW Serie 3 318d",
    brand: "BMW",
    model: "Serie 3",
    year: 2020,
    price: 24900,
    km: 62000,
    fuel: "Diesel",
    transmission: "Manuale",
    power: "150 CV",
    source: "subito",
    imageUrl: bmwImages[1],
    location: "Roma, RM",
    isNew: false,
    url: "#",
    priceRating: "good",
    color: "Bianco",
    doors: 4,
    bodyType: "Berlina",
  },
  {
    id: "3",
    title: "Audi A4 Avant 2.0 TDI",
    brand: "Audi",
    model: "A4",
    year: 2022,
    price: 35900,
    km: 28000,
    fuel: "Diesel",
    transmission: "Automatico",
    power: "163 CV",
    source: "automobile",
    imageUrl: images[2],
    location: "Torino, TO",
    isNew: false,
    url: "#",
    priceRating: "good",
    color: "Grigio",
    doors: 5,
    bodyType: "Station Wagon",
  },
  {
    id: "4",
    title: "Tesla Model 3 Long Range",
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    price: 38900,
    km: 15000,
    fuel: "Elettrica",
    transmission: "Automatico",
    power: "351 CV",
    source: "brumbrum",
    imageUrl: images[3],
    location: "Bologna, BO",
    isNew: false,
    url: "#",
    isBestDeal: true,
    priceRating: "best",
    color: "Rosso",
    doors: 4,
    bodyType: "Berlina",
  },
  {
    id: "5",
    title: "Fiat 500 Elettrica",
    brand: "Fiat",
    model: "500",
    year: 2023,
    price: 22500,
    km: 8000,
    fuel: "Elettrica",
    transmission: "Automatico",
    power: "118 CV",
    source: "autoscout24",
    imageUrl: images[4],
    location: "Napoli, NA",
    isNew: false,
    url: "#",
    priceRating: "normal",
    color: "Blu",
    doors: 3,
    bodyType: "Citycar",
  },
  {
    id: "6",
    title: "Mercedes-Benz Classe A 200d",
    brand: "Mercedes-Benz",
    model: "Classe A",
    year: 2021,
    price: 27800,
    km: 38000,
    fuel: "Diesel",
    transmission: "Automatico",
    power: "150 CV",
    source: "subito",
    imageUrl: images[5],
    location: "Firenze, FI",
    isNew: false,
    url: "#",
    priceRating: "good",
    color: "Argento",
    doors: 5,
    bodyType: "Crossover",
  },
  {
    id: "7",
    title: "Volkswagen Golf 8 1.5 TSI",
    brand: "Volkswagen",
    model: "Golf",
    year: 2022,
    price: 23400,
    km: 32000,
    fuel: "Benzina",
    transmission: "Manuale",
    power: "150 CV",
    source: "automobile",
    imageUrl: images[0],
    location: "Padova, PD",
    isNew: false,
    url: "#",
    isBestDeal: true,
    priceRating: "best",
    color: "Nero",
    doors: 5,
    bodyType: "Berlina",
  },
  {
    id: "8",
    title: "Toyota Yaris Cross Hybrid",
    brand: "Toyota",
    model: "Yaris Cross",
    year: 2023,
    price: 26900,
    km: 12000,
    fuel: "Ibrida",
    transmission: "Automatico",
    power: "116 CV",
    source: "brumbrum",
    imageUrl: images[1],
    location: "Verona, VR",
    isNew: false,
    url: "#",
    priceRating: "normal",
    color: "Bianco",
    doors: 5,
    bodyType: "SUV",
  },
  {
    id: "9",
    title: "BMW Serie 4 420d Coupé",
    brand: "BMW",
    model: "Serie 4",
    year: 2022,
    price: 38500,
    km: 25000,
    fuel: "Diesel",
    transmission: "Automatico",
    power: "190 CV",
    source: "autoscout24",
    imageUrl: bmwImages[2],
    location: "Milano, MI",
    isNew: false,
    url: "#",
    isBestDeal: true,
    priceRating: "best",
    color: "Nero",
    doors: 2,
    bodyType: "Coupé",
  },
  {
    id: "10",
    title: "BMW Serie 4 430i Gran Coupé",
    brand: "BMW",
    model: "Serie 4",
    year: 2023,
    price: 44900,
    km: 12000,
    fuel: "Benzina",
    transmission: "Automatico",
    power: "245 CV",
    source: "automobile",
    imageUrl: bmwImages[3],
    location: "Roma, RM",
    isNew: false,
    url: "#",
    priceRating: "good",
    color: "Grigio",
    doors: 4,
    bodyType: "Berlina",
  },
  {
    id: "11",
    title: "BMW Serie 4 M440i xDrive",
    brand: "BMW",
    model: "Serie 4",
    year: 2021,
    price: 52000,
    km: 35000,
    fuel: "Benzina",
    transmission: "Automatico",
    power: "374 CV",
    source: "subito",
    imageUrl: bmwImages[4],
    location: "Torino, TO",
    isNew: false,
    url: "#",
    priceRating: "normal",
    color: "Blu",
    doors: 2,
    bodyType: "Coupé",
  },
  {
    id: "12",
    title: "BMW Serie 4 420d xDrive Coupé",
    brand: "BMW",
    model: "Serie 4",
    year: 2023,
    price: 42800,
    km: 8000,
    fuel: "Diesel",
    transmission: "Automatico",
    power: "190 CV",
    source: "brumbrum",
    imageUrl: bmwImages[5],
    location: "Bologna, BO",
    isNew: false,
    url: "#",
    isBestDeal: true,
    priceRating: "best",
    color: "Bianco",
    doors: 2,
    bodyType: "Coupé",
  },
  {
    id: "13",
    title: "BMW Serie 4 430i Cabrio",
    brand: "BMW",
    model: "Serie 4",
    year: 2022,
    price: 48500,
    km: 18000,
    fuel: "Benzina",
    transmission: "Automatico",
    power: "245 CV",
    source: "autoscout24",
    imageUrl: bmwImages[0],
    location: "Napoli, NA",
    isNew: false,
    url: "#",
    priceRating: "good",
    color: "Rosso",
    doors: 2,
    bodyType: "Cabrio",
  },
  {
    id: "14",
    title: "BMW Serie 4 420d Gran Coupé",
    brand: "BMW",
    model: "Serie 4",
    year: 2021,
    price: 35900,
    km: 42000,
    fuel: "Diesel",
    transmission: "Automatico",
    power: "190 CV",
    source: "subito",
    imageUrl: bmwImages[1],
    location: "Firenze, FI",
    isNew: false,
    url: "#",
    priceRating: "good",
    color: "Argento",
    doors: 4,
    bodyType: "Berlina",
  },
  {
    id: "15",
    title: "BMW Serie 4 M440i Gran Coupé",
    brand: "BMW",
    model: "Serie 4",
    year: 2023,
    price: 58000,
    km: 5000,
    fuel: "Benzina",
    transmission: "Automatico",
    power: "374 CV",
    source: "automobile",
    imageUrl: bmwImages[2],
    location: "Padova, PD",
    isNew: false,
    url: "#",
    priceRating: "normal",
    color: "Nero",
    doors: 4,
    bodyType: "Berlina",
  },
  {
    id: "16",
    title: "BMW Serie 4 420d Coupé M Sport",
    brand: "BMW",
    model: "Serie 4",
    year: 2022,
    price: 41200,
    km: 30000,
    fuel: "Diesel",
    transmission: "Automatico",
    power: "190 CV",
    source: "brumbrum",
    imageUrl: bmwImages[3],
    location: "Verona, VR",
    isNew: false,
    url: "#",
    priceRating: "good",
    color: "Grigio",
    doors: 2,
    bodyType: "Coupé",
  },
];
