project_id = "zmtvsgekbxrbkeeznsuq"

[functions.scrape-listings]
verify_jwt = true

[functions.firecrawl-scrape]
verify_jwt = true

[functions.scrape-detail]
verify_jwt = true

[functions.ai-search]
verify_jwt = true
